import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Component/SheardComponent/Header";
import Footer from "@/Component/SheardComponent/Footer";
import Layout from "@/Component/Layout";
import toast, { Toaster } from 'react-hot-toast';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sofi E-commerse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
   <Layout>

     <Header />
        {children}
        <Footer />
<Toaster 
  position="bottom-right"
  toastOptions={{
    style: {
      background: '#363636',
      color: '#fff',
    },
    success: {
      duration: 3000,
      style: {
        background: '#22c55e',
        color: '#fff',
      },
    },
    error: {
      duration: 4000,
      style: {
        background: '#ef4444',
        color: '#fff',
      },
    },
    loading: {
      duration: 2000,
      style: {
        background: '#3b82f6',
        color: '#fff',
      },
    },
  }}
/>
   </Layout>
      </body>
    </html>
  );
}